---
title: "NeCSA Data Exploration"
author: "Laurie Baker and Matt Clayton"
date: "1/31/2022"
output: 
  html_document:
    toc: True
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r libraries, echo = FALSE}

library(tidyverse)
library(readr)
library(leaflet)
library(dplyr)

```


## Data Overview

```{r data import, echo = FALSE}

temperature_df <- read_csv("data/NeCSA_data_template_Temperature_Data.csv")
transect_df <- read_csv("data/NeCSA_data_template_Horizontal_Transect_Data.csv")
column_meta_data <- read_csv("data/NeCSA_data_template_Column_Metadata.csv")

```


### Temperature Data
```{r explore temperature data}

glimpse(temperature_df)

```

### Transect Data

```{r explore transect data}

glimpse(transect_df)

```

### Column Meta Data

```{r explore meta data}

glimpse(column_meta_data)

```

## Plots

### Water Temperature Ranges at Each NeCSA Field Station

```{r temp-range-by-facility, echo = FALSE}

temperature_df %>%
  ggplot(mapping = aes(x = `Field Station`, 
                       y = `Water Temperature`,
                       fill = `Field Station`)) +
  geom_violin() +
  labs(title = "Ranges of Recorded Water Temperatures",
       subtitle = "By NeCSA Field Station",
       y = "Water Temperature (Celsius)") +
  theme(legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow=3))
  
```

### Water Temperature at Each NeCSA Field Station Over Time

```{r temp-vs-time-by-station, echo = FALSE}

# Reformat dates

temperature_df$betterDates <- as.Date(temperature_df$Date, format = "%m-%d-%Y")

# Create line plot of water temperature by field station over time

temperature_df %>%
  ggplot(mapping = aes(x = betterDates, 
                       y = `Water Temperature`,
                       colour = `Field Station`)) +
  geom_line() +
  labs(title = "Recorded Water Temperature Over Time",
       subtitle = "By NeCSA Field Station",
       y = "Water Temperature (Celsius)",
       x = "Date") +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  guides(colour = guide_legend(nrow=3)) +
  scale_x_date(date_breaks = "2 months" , date_labels = "%b-%y") +
  guides(x =  guide_axis(angle = 45))

```

### Water Temperature Over Time (All Stations)

```{r temp-vs-time-all-stations, echo = FALSE}

# Reformat dates

temperature_df$betterDates <- as.Date(temperature_df$Date, format = "%m-%d-%Y")

# Create line plot of water temperature (all field stations)

temperature_df %>%
  ggplot(mapping = aes(x = betterDates, 
                       y = `Water Temperature`)) +
  geom_line(color = "blue") +
  labs(title = "Recorded Water Temperature Over Time",
       y = "Water Temperature (Celsius)",
       x = "Date") +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  scale_x_date(date_breaks = "2 months" , date_labels = "%b-%y") +
  guides(x =  guide_axis(angle = 45))

```

### Water Temperature Over Time Faceted by Field Station

```{r temp-vs-time-by-facility-faceted, echo = FALSE}

# Create faceted line plot of water temperature by field station over time

temperature_df %>%
  ggplot(mapping = aes(x = betterDates, 
                       y = `Water Temperature`,
                       color = `Field Station`)) +
  geom_line(show.legend = FALSE) +
  facet_wrap(~ `Field Station`, ncol = 2) +
  labs(title = "Recorded Water Temperature Over Time",
       subtitle = "Faceted By NeCSA Field Station",
       y = "Water Temperature (Celsius)",
       x = "Date") +
  scale_x_date(date_breaks = "3 months" , date_labels = "%b-%y") +
  guides(x =  guide_axis(angle = 30))

```

### Location of Each NeCSA Field Station on Gulf of Maine Leaflet

```{r field-stations-leaflet, echo = FALSE}

# Create df for field station locations

field_stations <- temperature_df %>%
  group_by(`Field Station`) %>%
  select(`Field Station`, Longitude, Latitude) %>%
  distinct()

# Create labels for leaflet

labels <- sprintf(
  "<strong>%s</strong><br/>",
    field_stations$`Field Station` %>%
      lapply(htmltools::HTML)) 

# Generate Gulf of Maine leaflet indicating location of each field station

leaflet(field_stations) %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.OceanBasemap) %>%
  addMarkers(~Longitude, ~Latitude, popup = labels) %>%
    setView(lng = -69, lat = 43.7, zoom = 7.5) 

```

```{r species-count-by-quadrat-faceted, echo = FALSE}

# Create data frame that only includes quadrats with observed species

transect_df_filter <- transect_df %>%
  filter(`# per quadrat` >= 1) %>%
  filter(`# per quadrat` != "ND") %>%
  select(`Field Station`, Quadrat, Date, `# per quadrat`, `Species Name`)
  
# Generate new variable for observation year

transect_df_filter$Year <- format(as.Date(transect_df_filter$Date, format="%m-%d-%Y"),"%Y")

# Generate new variable for average observations per quadrat per year 

transect_df_filter <- transect_df_filter %>%
  group_by(Quadrat, Year) %>%
  mutate(`#_mean` = (mean(as.numeric(`# per quadrat`)))) 

# Limit decimal points to 2 (average observations variable)

transect_df_filter$`#_mean` <- format(round(transect_df_filter$`#_mean`, 2), nsmall = 2)

# Convert #_mean to numeric variable

transect_df_filter$`#_mean` <- as.numeric(transect_df_filter$`#_mean`)

# Create bar plot of average species per quadrat per year
# Green crabs are the only observed species in the dataset
  
ggplot(transect_df_filter, aes(x = factor(Quadrat), y = `#_mean`, fill = Year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Quadrat Number",
       y = "Mean Yearly Observations",
       title = "Mean Yearly Green Crab Observations per Quadrat",
       subtitle = "Grouped by Year",
       caption = "Note: Only quadrats with non-zero values are displayed (quadrats 2, 15, 21, and 24 omitted)")


```
